### ISSUE TITLE
FIRE workflow - Historical fire data

### ISSUE THREAD

**Issue by fsmikaela** [CLIMAAX/FIRE#3]
Hello,

We are interested in running the FIRE workflow for Crete, Greece and I saw that the sample area is limited to the Catalonia region. 
I wanted to ask if the historical fire input datasets, used in the hazard workflow, are available for the pan-European region in the same temporal resolution. I believe the data on the EFFIS data portal (which is temporarily down for maintenance) only run back to 2016 for Greece. Could you please provide the uncut datasets or tell me where I can find them?

Thank you for any help you can offer.

**Comment by farzadazma** [comment]
Hi there, I downloaded recently the fire data from the EFFIS portal, I double checked now and it has data from 2008 to 2023. If you want I can share the data with you, otherwise you can download it directly from EFFIS.

**Comment by farzadazma** [comment]
you can download it from here: https://we.tl/t-4dGbGFFKgB

**Comment by fsmikaela** [comment]
Thank you so much!
